### PR TITLE
Customise starter

### PR DESCRIPTION
**Pull request by abyrne10**
Add workflow features like eslint, VS Code debugging, yarn.lock and code coverage reports, and refactor function architecture to separate handlers from business logic.

### CODE REVIEW

**Comment by jayair** [comment]
@abyrne10 This looks pretty useful. How come you closed it?

**Comment by abyrne10** [comment]
> @abyrne10 This looks pretty useful. How come you closed it?

@jayair I forked this repo to do some customising, as I was using it a lot for my own projects, but accidentally made the pull request for this repo, not my forked version (hence things like the updated readme, AWS region and eslint rules). I would be happy to open a new pull request with any changes that you think would be useful, please le me know!

**Comment by jayair** [comment]
@abyrne10 Can I get a link to your repo? I'd love to take a look.

**Comment by abyrne10** [comment]
Here it is:
https://github.com/bouncetechnologies/serverless-nodejs-starter
Would be very happy to get your feedback on it. One of the main reasons I structured it this way was to separate the handlers from the business logic, with one of the advantages being that it makes testing easier, as I can inject mocks instead of database libraries (for example).

**Comment by jayair** [comment]
Cool. Thanks for putting it up. I'll check it out!

**Pull request closed without merging**
